[build]
  publish = "."
  functions = "netlify/functions"

# netlify.toml




# Redirección de URLs viejas a la nueva lógica dinámica
[[redirects]]
  from = "/proyecto/macro"
  to = "/project-viewer.html?key=macro_lan"
  status = 200

[[redirects]]
  from = "/proyecto/sdwan"
  to = "/project-viewer.html?key=sdwan_nubes"
  status = 200

[[redirects]]
  from = "/proyecto/storage"
  to = "/project-viewer.html?key=storage_backup"
  status = 200

# Protección para la función de datos
[[redirects]]
  from = "/.netlify/functions/presentation-data"
  to = "/.netlify/functions/presentation-data"
  status = 200
  force = true


# Headers extra
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
